language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mohiit/dotut-client-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -r CI=true mohiit/dotut-client-test npm test -- --coverage

after_success:
  - docker build mohiit/dotut-mc-nginx ./nginx
  - docker build mohiit/dotut-mc-server ./server
  - docker build mohiit/dotut-mc-worker ./worker
  - docker build mohiit/dotut-mc-client ./client