language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mohiit/dotut-client-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -r CI=true mohiit/dotut-client-test npm test -- --coverage

after_success:
  - docker build mohiit/dotut-mc-nginx ./nginx
  - docker build mohiit/dotut-mc-server ./server
  - docker build mohiit/dotut-mc-worker ./worker
  - docker build mohiit/dotut-mc-client ./client
  # login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to the dockerhub
  - docker push mohiit/dotut-mc-nginx 
  - docker push mohiit/dotut-mc-server
  - docker push mohiit/dotut-mc-worker
  - docker push mohiit/dotut-mc-client

